INFO_LEVEL: INFO  # DEBUG, INFO, ERROR

collect:
  # 用于文件夹命名
  save_dir: ./data/
  task_name: swave_the_rubbish
  type: 7-10
  # eg.
  # save_dir: ./data/
  # task_name: stack_bowls
  # type: test
  # 保存路径: data/stack_bowls/test/***.hdf5

  save_format: hdf5
  num_episode: 50

  save_freq: 30
  skip_silent_frame: true

robot:
  type: dual_alicia_teleop_robot
  control_mode: joint
  MASTER_PORT:
    left_arm: "/dev/ttyACM0"
    right_arm: "/dev/ttyACM1"
  SLAVE_PORT:
    left_arm: "can_left"
    right_arm: "can_right"
  CAMERA_SERIALS:
    head: "261222074970"
    left: "/dev/left-camera"
    right: "/dev/right-camera"
  # 仅用于 reset() 初始化模拟操作臂（TestArmController）
  init_qpos:
    master_left_arm: [0, 0, 0.78, 0, -1.57, 0]
    master_right_arm: [0, 0, 0.78, 0, -1.57, 0]

    slave_left_arm: [0, 0, 0, 0, 0, 0]
    slave_left_gripper: 1.0
    slave_right_arm: [0, 0, 0, 0, 0, 0]
    slave_right_gripper: 1.0
